### ISSUE TITLE
Rxvlan options are filled incorrectly

### ISSUE THREAD

**Issue by ikoveshnikov** [ebirger/netpen#8]
If a rxvlan/txvlan option is configured for interface, it's incorrectly set in bash script.

Here is configuration I have:

```yaml
items:
  - netns:
      name: sut
      forwarding: true
  - netns:
      name: generator
      forwarding: true
  - veth:
      name: eth0
      dev1:
        netns: netns.sut
        ethtool:
          rxvlan: off
          txvlan: off
      dev2:
        netns: netns.generator
        ethtool:
          rxvlan: off
          txvlan: off
settings:
  title: Great Plan
```

And resulting bash script:
```sh
#!/bin/bash -e

# ... 

sysctl -w net.ipv4.route.mtu_expires=15


# netns
ip netns add sut
ip netns exec sut sysctl -w net.ipv4.conf.all.forwarding=1
ip netns exec sut sysctl -w net.ipv6.conf.all.forwarding=2
ip netns add generator
ip netns exec generator sysctl -w net.ipv4.conf.all.forwarding=1
ip netns exec generator sysctl -w net.ipv6.conf.all.forwarding=2

# veth
ip link add eth0.dev1 netns sut type veth peer name eth0.dev2 netns generator
ip -net sut link set eth0.dev1 up
ip netns exec sut ethtool -K eth0.dev1 rxvlan on
ip netns exec sut ethtool -K eth0.dev1 txvlan on
ip -net generator link set eth0.dev2 up
ip netns exec generator ethtool -K eth0.dev2 rxvlan on
ip netns exec generator ethtool -K eth0.dev2 txvlan on

# routes
```

Option ` rxvlan on` is set on both interfaces.
